name: Spustit srážkového agenta

on:
  schedule:
    - cron: '34 18 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Stazeni repozitare
        uses: actions/checkout@v4

      - name: Nastaveni Pythonu
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalace knihoven
        run: pip install -r requirements.txt

      - name: Spusteni skriptu
        run: python agent.py

      # TADY JSME UPRAVILI NÁZEV SOUBORU NA VŠECHNY STANICE:
      - name: Ulozeni vysledneho souboru
        uses: actions/upload-artifact@v4
        with:
          name: srazky-vsechny-stanice-csv
          path: srazky_vsechny_stanice.csv
